# Generated by Django 4.1.5 on 2023-02-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('motogp_titles', models.IntegerField()),
                ('moto2_titles', models.IntegerField()),
                ('moto3_titles', models.IntegerField()),
                ('moto3_debut', models.DateField()),
                ('moto2_debut', models.DateField()),
                ('motogp_debut', models.DateField()),
                ('team', models.CharField(max_length=50)),
                ('about_rider', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('bike', models.CharField(max_length=30)),
                ('constructor_titles', models.IntegerField()),
                ('sponsor', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=300)),
                ('old_riders', models.CharField(max_length=500)),
                ('current_riders', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_rider', to='motogp.rider')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='old_teams',
            field=models.ManyToManyField(related_name='old_team', to='motogp.team'),
        ),
    ]
