# Generated by Django 4.1.5 on 2023-02-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motogp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='current_riders',
        ),
        migrations.AddField(
            model_name='team',
            name='riders',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='about_rider',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motogp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='history',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='old_riders',
            field=models.TextField(max_length=500),
        ),
    ]
