# Generated by Django 4.1.5 on 2023-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motogp', '0002_remove_team_current_riders_team_riders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='riders',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
