# Generated by Django 4.1.5 on 2023-02-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motogp', '0003_alter_team_riders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
